TRUNCATE TAG, ROLE CASCADE;

INSERT INTO TAG (NAME) VALUES('FUN');
INSERT INTO TAG (NAME) VALUES('TRIPS');
INSERT INTO TAG (NAME) VALUES('TRAVELLING');
INSERT INTO TAG (NAME) VALUES('READING');
INSERT INTO TAG (NAME) VALUES('BEST');

INSERT INTO ROLE (NAME) VALUES ('ROLE_USER');