CREATE TABLE CERTIFICATE (
    id SERIAL  PRIMARY KEY ,
    NAME           VARCHAR(50)   NOT NULL UNIQUE,
    DESCRIPTION    VARCHAR(200)     NOT NULL,
    PRICE        NUMERIC NOT NULL CHECK(PRICE >0),
    CREATION_DATE         DATE NOT NULL,
	MODIFICATION_DATE DATE,
    VALID_DAYS INT CHECK (VALID_DAYS > 0)
);

CREATE TABLE TAG (
    ID SERIAL  PRIMARY KEY ,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE CERTIFICATE_TAG (
    CERTIFICATE_ID INTEGER REFERENCES CERTIFICATE(ID) ON DELETE CASCADE,
	TAG_ID INTEGER REFERENCES TAG(ID) ON DELETE CASCADE,
	PRIMARY KEY (CERTIFICATE_ID, TAG_ID)
);
