INSERT INTO CERTIFICATE(NAME, DESCRIPTION, PRICE, CREATION_DATE, VALID_DAYS) VALUES ('Computer', 'Discount for Computer', 10, '2020.02.02', 50);
INSERT INTO CERTIFICATE(NAME, DESCRIPTION, PRICE, CREATION_DATE, VALID_DAYS) VALUES ('Hair style', 'Hair style', 50, '2020.02.02', 80);
INSERT INTO CERTIFICATE(NAME, DESCRIPTION, PRICE, CREATION_DATE, VALID_DAYS) VALUES('Cocktail bar', 'bar', 45, '2020.02.02', 55);

INSERT INTO TAG (NAME) VALUES('FUN');
INSERT INTO TAG (NAME) VALUES('TRIPS');
INSERT INTO TAG (NAME) VALUES('TRAVELLING');
INSERT INTO TAG (NAME) VALUES('READING');
INSERT INTO TAG (NAME) VALUES('BEST');
